[project]
name = "huggingface-data-rawification"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "huggingface-hub>=0.35.3",
    "polars>=1.34.0",
    "tqdm>=4.67.1",
]
